name: my_habit_tracker
description: A Habit Tracker App with Streaks, Stats, Filter, and Personalization.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: any
  fl_chart: ^0.60.0  # Für Balkendiagramme

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
